# Generated by Django 5.2.8 on 2025-12-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_friendship_friendship_unique_friendship_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularityProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Popularity dashboard',
                'verbose_name_plural': 'Popularity dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.pin',),
        ),
    ]
